#define EIER_CANTCREATE_FONT 1
#define EIER_CANTINIT_DIRECTDRAW 2
#define EIER_CANTINIT_DDSURFACE 3
#define EIER_CANTCREATE_TEXTDIB 4
#define EIER_CANTOPENFILE 5
#define EIER_CANTALLOCMEMORY 6
#define EIER_CANTWRITEFILE 7
#define EIER_CANTREADFILE 8

#define EIER_NOSUPORTCOLOR 101

//---eiDib
#define EIER_DIB_CANTOPEN EIER_CANTOPENFILE
#define EIER_DIB_NOSUPORTCOLOR EIER_NOSUPORTCOLOR
#define EIER_DIB_CANTALLOC EIER_CANTALLOCMEMORY
#define EIER_DIB_CANTCREATE 1004
#define EIER_DIB_NOTDIB 1005
#define EIER_DIB_CANTWRITEFILE EIER_CANTWRITEFILE
#define EIER_DIB_CANTREADFILE EIER_CANTREADFILE
